meta_product_name: "MatchLab"
meta_title: "MatchLab - Bringing players together"
meta_description: "MatchLab is a unique website designed to pair various racket-sports players with competitors of a similar skill level. Using our proprietary ranking algorithms, we allow tennis, squash or badminton players to find a match at a similar proficiency, within a distance they choose."
meta_image: "cover.png" # should exist in `app/assets/images/`
